### ISSUE TITLE
Ajustes de layout na página inicial

### ISSUE THREAD

**Issue by avaloni** [culturagovbr/id-cultura#1]
Botão "Entrar" do formulário de login está muito grande e fora do padrão

Checkbox de "Manter Conectado" não está alinhado

**Comment by raissagal** [comment]
Use contas de outros serviços está desajustado com o tamanho da tela. Na tela inicial só aparece o seu título e não o resto das informações, tem que subir as opções de redes sociais pras pessoas não terem que descer a rolagem pra poder acessar

**Comment by raissagal** [comment]
abaixo de IDCultura integrando serviços digitais tem que vir algo mais explicativo do que é isso. 
Sugestão: "Acesse todos os recursos do Ministério da Cultura só com um login"

**Comment by raissagal** [comment]
textos repetitivos:

"Você pode criar uma Conta do ID cultura na página inicial do ID cultura ou clicando em Cadastre-se no sistema, na página de login. Você pode usar sua Conta do ID cultura com todos os serviços da Cultura."
