### ISSUE TITLE
links do twitter e google estão invertidos.

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/id-cultura#10]
até teria trocado, mas não achei onde edita a "capa". alguém cola aqui?

**Comment by avaloni** [comment]
É nesse html aqui https://github.com/culturagovbr/id-cultura/blob/redeculturaviva/src/PROCERGS/LoginCidadao/CoreBundle/Resources/views/Default/index.html.twig

Vou fechar porque está duplicado #2
