### ISSUE TITLE
atualizar mensagens de email para xs inscritxs

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/id-cultura#15]
login_cidadao naoresponda@cultura.gov.br
18:19 (Há 3 horas)

para mim 
Login Cidadão  

Olá, 11915986495610464ac199a5.95777064!

Para completar a validação da sua conta clique no botão a seguir.

Confirmar Email

**Comment by avaloni** [comment]
Corrigido em 70759bc3
