### ISSUE TITLE
Copyleft @2014 Governo do Rio Grande do Sul

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/id-cultura#16]
rodapé ao tentar cadastrar com facebook
http://id.cultura.gov.br/facebook/login_check?code=AQDaqDxju5rcs6LlloSPN3NhYMQjAMDYDPVvV3KRQeNuEzkAvizKhsKOyG9lVyZ_gVbzYbQZQTi6EAZamWeVwyf3RvVBA6fPugiNkUkl5wL5nIA0ctNCUqOaQRKf6URMNicEOwgI7eO8SkMwtJ5GJ--ZmBvmUkzLvx6LSGg6Y5ytx3qTdMHGL4YghcT2j2iwGvzGgswLCAFNWTQmi_-k560idEhlSOFzs_ZKpMXZUR0F3oAiBSxfEyPB8S-LKgaDTWdMk_QqiTNfDxfFnmy5KaAZg-J_byw5Xiv0J3841wG5ECfkQrI0wOr0WB59cZKw5mB1fcbCwBtAzOr0RBivBW4x&state=6cbcdf9a61bcdd9a38f4bf959ae3d15a#_=_

**Comment by avaloni** [comment]
Corrigido em 06455290
