### ISSUE TITLE
Alternar entre form de cadastro e de acesso

### ISSUE THREAD

**Issue by avaloni** [culturagovbr/id-cultura#3]
Hoje, só é possível abrir o form de acesso, caso queira voltar ao form de cadastro só recarregando a página

**Comment by nitaibezerra** [comment]
Uma forma de resolver é reusando o botão "Entrar" trocando o nome para "Criar conta". Talvez modificar a cor para verde ajude a destacar a mudança de estado.

**Comment by fernao** [comment]
sugestao de tom de verde?
