### ISSUE TITLE
Botão de logar com Facebook não funciona

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/id-cultura#5]
De acordo com @guilhermednt pode ser bloqueio de firewall de acesso do servidor ao Facebook

**Comment by guilhermednt** [comment]
Na verdade eu olhei depois e o facebook não está enviando o email do usuário. Nunca passei por isso mas deve ter algum tipo de aviso de alguma informação faltando no [dashboard do facebook](https://developers.facebook.com/).

**Comment by jpmehl** [comment]
Fui me cadastrar com o Facebook para testes, deu pau e ficou rodando nesta tela, por mais que eu desse um OK, ele me mantinha neste mesmo erro. 

![erro-cadastro-idcultura-facebook](https://cloud.githubusercontent.com/assets/4163139/19248525/f8690dcc-8f06-11e6-822d-1001d1d3358e.png)
